# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - nightly
notifications:
  email: false
codecov: true
coveralls: true
before_script: julia --project=docs -e '
        using Pkg;
        Pkg.add(PackageSpec(url="https://github.com/ChitambarLab/QBase.jl", rev="master"));'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/ChitambarLab/QBase.jl", rev="master"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
